HotelProject/Models/Propertie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelProject.Models
{
    public class Propertie
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Название")]
        [Required(ErrorMessage = "Не указано название")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Title { get; set; }
        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Не указано описание")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Description { get; set; }
        [Display(Name = "Изображение")]
        public string Image { get; set; }

        [NotMapped]
        public bool isChecked { get; set; }

    }
}

HotelProject/Controllers/PropertieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace HotelProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class PropertieController : Controller
    {
        HotelContext db;
        IHostingEnvironment _appEnvironment;
        public PropertieController(HotelContext context, IHostingEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
            db = context;
        }
        public IActionResult Propertie_Index()
        {
            return View(db.Properties.ToList());
        }

        public async Task<IActionResult> Propertie_Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propertie = await db.Properties
                .FirstOrDefaultAsync(m => m.Id == id);
            if (propertie == null)
            {
                return NotFound();
            }

            return View(propertie);
        }
        [HttpGet]
        public IActionResult Propertie_Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Propertie_Add([Bind("Id,Title,Description")] Propertie propertie, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadedFile != null)
                {
                    string path = "/files/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    propertie.Image = path;
                }

                db.Properties.Add(propertie);
                db.SaveChanges();

                TempData["Propertie Add"] = "Вы добавили новое свойство";

                return RedirectToAction("Propertie_Index");
            }
            return View(propertie);
        }
        [HttpGet]
        public IActionResult Propertie_Edit(int id)
        {
            Propertie propertie = db.Properties.Find(id);
            return View(propertie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Propertie_Edit([Bind("Id,Title,Description")] Propertie propertie, IFormFile uploadedFile)
        {
            db.Entry(propertie).State = EntityState.Modified;
            if (ModelState.IsValid)
            {
                if (uploadedFile != null)
                {
                    string path = "/files/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    propertie.Image = path;
                }

                db.SaveChanges();
                TempData["Propertie Edit"] = "Вы изменили свойство";
                return RedirectToAction("Propertie_Index");
            }
            return View(propertie);
        }
        [HttpGet]
        public IActionResult Propertie_Delete(int id)
        {
            Propertie b = db.Properties.Find(id);
            return View(b);
        }

        [HttpPost, ActionName("Propertie_Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Propertie_DeleteConfirmed(int id)
        {
            Propertie b = db.Properties.Find(id);

            db.Properties.Remove(b);
            db.SaveChanges();
            TempData["Propertie Delete"] = "Вы удалили свойство";
            return RedirectToAction("Propertie_Index");
        }
    }
}

HotelProject/Views/Propertie/Propertie_Add.cshtml
@model HotelProject.Models.Propertie
@{
    ViewData["Title"] = "Propertie_Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Добавить</h2>

<h4>Свойство</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Propertie_Add" asp-controller="Propertie" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Название</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Изображение</label>
                <input type="file" name="uploadedFile" id="UploadFile" />
                <img id="imgpreview" src="~/files/no_image.png" />
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Cвойства", "Propertie_Index")
</div>

@section Scripts
{
    <script src="~/js/ProductScript.js"></script>
}
















@*<!DOCTYPE html>
     <html>
        <head>
            <title>Добавление свойств</title>
        </head>
        <body>
            <div>
                <h3>Добавление свойств</h3>
                @using (Html.BeginForm())
                {
                    @Html.LabelFor(model => model.Title, "Название опции")
                    <br />
                    @Html.EditorFor(model => model.Title)
                    <br /><br />
                    @Html.LabelFor(model => model.Description, "Описание")
                    <br />
                    @Html.EditorFor(model => model.Description)
                    <br /><br />
                    @Html.LabelFor(model => model.Image, "Картинка")
                    <br />
                    @Html.EditorFor(model => model.Image)
                    <br /><br />
                    <input type="submit" value="Добавить" />
                }
            </div>
        </body>
    </html>*@

HotelProject/Views/Propertie/Propertie_Delete.cshtml
@model HotelProject.Models.Propertie
@{
    ViewData["Title"] = "Propertie_Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Удаление</h2>
<div>
    <h4>Свойство</h4>
    <dl class="dl-horizontal">
        <dt>Название: </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>Описание: </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>Картинка: </dt>
        <dd>
            <img src="@Url.Content(Model.Image)" />
        </dd>
    </dl>
    <form asp-action="Propertie_Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
    </form>
</div>

<div>
    @Html.ActionLink("Свойства", "Propertie_Index")
</div>

HotelProject/Views/Propertie/Propertie_Details.cshtml
@model HotelProject.Models.Propertie

@{
    ViewData["Title"] = "Propertie_Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детализация</h2>

<div>
    <h4>Свойства</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image):
        </dt>
        <dd>
            @if (Model.Image != null)
            {
                <img src="@Url.Content(Model.Image)" />
            }
            else
            {
                <img id="imgpreview" src="~/files/no_image.png" />
            }
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Свойства", "Propertie_Index")
</div>

HotelProject/Views/Propertie/Propertie_Edit.cshtml
@model HotelProject.Models.Propertie
@{
    ViewData["Title"] = "Propertie_Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Редактирование</h2>

<h4>Свойство</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Propertie_Edit" method="post" asp-controller="Propertie" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" value="@ViewBag.PropertieId" name="ProductId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Название</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
             </div>
             <div class="form-group">
                    <label class="control-label">Изображение</label>
                    <input type="file" name="uploadedFile" id="UploadFile" />
                    <img id="imgpreview" src="@Url.Content(Model.Image)" />
              </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Свойства", "Propertie_Index")
</div>

@section Scripts
{
    <script src="~/js/ProductScript.js"></script>
}

HotelProject/Views/Propertie/Propertie_Index.cshtml
@model IEnumerable<HotelProject.Models.Propertie>
@{
    ViewData["Title"] = "Propertie_Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Свойства</h2>


@if (TempData["Propertie Add"] != null)
{
<div class="alert alert-success">
    @TempData["Propertie Add"]
</div>
}
@if (TempData["Propertie Edit"] != null)
{
    <div class="alert alert-success">
        @TempData["Propertie Edit"]
    </div>
}
@if (TempData["Propertie Delete"] != null)
{
    <div class="alert alert-success">
        @TempData["Propertie Delete"]
    </div>
}


<p>
    @Html.ActionLink("Создать новое свойство", "Propertie_Add", "", htmlAttributes: new { @class = "btn btn-success" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <p><img src="@Url.Content(item.Image)"></p>
                </td>
                <td>
                    <a asp-action="Propertie_Edit" asp-route-id="@item.Id">Редактировать</a> |
                    <a asp-action="Propertie_Details" asp-route-id="@item.Id">Детали</a> |
                    <a asp-action="Propertie_Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>