HotelProject/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace HotelProject.Models
{
    public class Request
    {
        public int Id { get; set; }
        [Display(Name = "Телефон")]
        [Required(ErrorMessage = "Не указан телефон")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Phone { get; set; }
        [Display(Name = "Почта")]
        [Required(ErrorMessage = "Не указана почта")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Email { get; set; }
        [Display(Name = "Время")]
        public DateTime DataTimeRequest { get; set; }
        [Display(Name = "Текст")]
        [Required(ErrorMessage = "Не указан текст")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Text { get; set; }

    }
}

HotelProject/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HotelProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace HotelProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class RequestController : Controller
    {
        HotelContext db;
        public RequestController(HotelContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View(db.Requests.ToList());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await db.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add([Bind("Id,Phone,Email,Text")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Requests.Add(request);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(request);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Request request = db.Requests.Find(id);
            return View(request);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,Phone,Email,Text")] Request request)
        {
            db.Entry(request).State = EntityState.Modified;
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Request b = db.Requests.Find(id);
            return View(b);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Option_DeleteConfirmed(int id)
        {
            Request b = db.Requests.Find(id);

            db.Requests.Remove(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HotelProject/Views/Request/Add.cshtml
@model HotelProject.Models.Request
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить</h2>

<h4>Request</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" asp-controller="Request" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Телефон</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Почта</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataTimeRequest" class="control-label">Время</label>
                <input asp-for="DataTimeRequest" class="form-control" />
                <span asp-validation-for="DataTimeRequest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label">Текст</label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Ответы", "Index")
</div>

HotelProject/Views/Request/Delete.cshtml
@model HotelProject.Models.Request
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Удаление</h2>
<div>
    <h4>Request</h4>
    <dl class="dl-horizontal">
        <dt>Название: </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>Описание: </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>Краткое описание: </dt>
        <dd>
            @Html.DisplayFor(model => model.DataTimeRequest)
        </dd>
        <dt>Картинка: </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
    </form>
</div>>

<div>
    @Html.ActionLink("Ответы", "Index")
</div>

HotelProject/Views/Request/Details.cshtml
@model HotelProject.Models.Request

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детализация</h2>

<div>
    <h4>Заявка</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Phone):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataTimeRequest):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataTimeRequest)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Text):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Заявки", "Index")
</div>

HotelProject/Views/Request/Edit.cshtml
@model HotelProject.Models.Request
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование</h2>

<h4>Request</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" asp-controller="Propertie" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" value="@ViewBag.PropertieId" name="PropertieId" />
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Телефон</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Почта</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataTimeRequest" class="control-label">Время</label>
                <input asp-for="DataTimeRequest" class="form-control" />
                <span asp-validation-for="DataTimeRequest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label">Текст</label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Ответы", "Index")
</div>

















@*<!DOCTYPE html>
    <html>
    <head>
        <title>Редактирование</title>
    </head>
    <body>
        <div>
            <h3>Редактор </h3>
            <form method="post">
                <input type="hidden" value="@ViewBag.RequestId" name="RequestId" />
                <fieldset>
                    @Html.HiddenFor(m => m.Id)
                    <p>
                        @Html.LabelFor(m => m.Phone, "Телефон")
                        <br />
                        @Html.EditorFor(m => m.Phone)
                    </p>
                    <p>
                        @Html.LabelFor(m => m.Email, "Почта")
                        <br />
                        @Html.EditorFor(m => m.Email)
                    </p>
                    <p>
                        @Html.LabelFor(m => m.DataTimeRequest, "Время")
                        <br />
                        @Html.EditorFor(m => m.DataTimeRequest)
                    </p>
                    <p>
                        @Html.LabelFor(m => m.Text, "Текст")
                        <br />
                        @Html.EditorFor(m => m.Text)
                    </p>
                    <p><input type="submit" value="Отправить" /></p>
                </fieldset>
            </form>
        </div>
    </body>
    </html>*@

HotelProject/Views/Request/Index.cshtml
@model IEnumerable<HotelProject.Models.Request>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Создать", "Add", "", htmlAttributes: new { @class = "btn btn-success" })
</p>
<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataTimeRequest)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a> |
                </td>
            </tr>
        }
    </tbody>
</table>


















@*<!DOCTYPE html>

    <html>
    <head>
        <title>Список запросов</title>
    </head>
    <body>
        <h3>Список запросов</h3>
        <table>
            <tr>
                <td>Телефон:</td>
                <td>Почта:</td>
                <td>Время:</td>
                <td>Текст:</td>

            </tr>
            @foreach (var request in Model)
            {
        <tr>
            <td>@request.Phone</td>
            <td>@request.Email</td>
            <td>@request.DataTimeRequest</td>
            <td>@request.Text</td>
            <td><a href="~/User/Edit/@request.Id">Изменить</a></td>
            <td><a href="~/User/Delete/@request.Id">Удалить</a></td>
        </tr>
            }
        </table>
    </body>
    </html>*@