HotelProject/Models/Option.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace HotelProject.Models
{
    public class Option
    {
        public int Id { get; set; }
        [Display(Name = "Название")]
        [Required(ErrorMessage = "Не указано название")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Title { get; set; }
        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Не указано описание")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "Недопустимая длина")]
        public string Description { get; set; }
        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Не указана цена")]
        public int Price { get; set; }
        [UIHint("Boolean")]
        [Display(Name = "Добавление")]
        public bool IsPublish { get; set; } 
    }
}

HotelProject/Controllers/OptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace HotelProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class OptionController : Controller
    {
        HotelContext db;
        public OptionController(HotelContext context)
        {
            db = context;
        }
        public IActionResult Option_Index()
        {
            return View(db.Options.ToList());
        }
        [HttpGet]
        public IActionResult Option_Add()
        {
            return View();
        }

        public async Task<IActionResult> Option_Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var option = await db.Options
                .FirstOrDefaultAsync(m => m.Id == id);
            if (option == null)
            {
                return NotFound();
            }

            return View(option);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Option_Add([Bind("Id,Title,Description,Price")] Option option)
        {
            if (ModelState.IsValid)
            {
                //уникальность заголовка и описания
                if (db.Options.Any(x => x.Title == option.Title))
                {
                    ModelState.AddModelError("", "Данный заголовок уже занят");
                    return View(option);
                }
                else if (db.Options.Any(x => x.Description == option.Description))
                {
                    ModelState.AddModelError("", "Данное описание уже занято");
                    return View(option);
                }


                db.Options.Add(option);

                TempData["Option Add"] = "Вы добавили новую опцию";
                db.SaveChanges();
                return RedirectToAction("Option_Index");
            }
            return View(option); 
        }
        [HttpGet]
        public IActionResult Option_Edit(int id)
        {
            Option option = db.Options.Find(id);
            return View(option);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Option_Edit([Bind("Id,Title,Description,Price")] Option option)
        {
            db.Entry(option).State = EntityState.Modified;
            if (ModelState.IsValid)
            {
                //уникальность заголовка и описания
                if (db.Options.Any(x => x.Title == option.Title))
                {
                    ModelState.AddModelError("", "Данный заголовок уже занят");
                    return View(option);
                }
                else if (db.Options.Any(x => x.Description == option.Description))
                {
                    ModelState.AddModelError("", "Данное описание уже занято");
                    return View(option);
                }

                db.SaveChanges();
                TempData["Option Edit"] = "Вы изменили опцию";
                return RedirectToAction("Option_Index");
            }
            return View(option);
        }

        [HttpGet]
        public IActionResult Option_Delete(int id)
        {
            Option b = db.Options.Find(id);
            return View(b);
        }

        [HttpPost, ActionName("Option_Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Option_DeleteConfirmed(int id)
        {
            Option b = db.Options.Find(id);

            db.Options.Remove(b);
            db.SaveChanges();
            TempData["Option Delete"] = "Вы удалили опцию";
            return RedirectToAction("Option_Index");
        }

    }
}

HotelProject/Views/Option/Option_Add.cshtml
@model HotelProject.Models.Option
@{
    ViewData["Title"] = "Option_Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавление</h2>

<h4>Опции</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Option_Add" asp-controller="Option" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Название</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Опции", "Option_Index")
</div>

HotelProject/Views/Option/Option_Delete.cshtml
@model HotelProject.Models.Option
@{
    ViewData["Title"] = "Option_Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Удаление</h2>
<div>
    <h4>Опции</h4>
    <dl class="dl-horizontal">
        <dt>Название: </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>Описание: </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>Цена: </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    <form asp-action="Option_Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
    </form>
</div>

<div>
    @Html.ActionLink("Опции", "Option_Index")
</div>

HotelProject/Views/Option/Option_Details.cshtml
@model HotelProject.Models.Option

@{
    ViewData["Title"] = "Option_Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детализация</h2>

<div>
    <h4>Опции</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPublish):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPublish)
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Опции", "Option_Index")
</div>

HotelProject/Views/Option/Option_Edit.cshtml
@model HotelProject.Models.Option
@{
    ViewData["Title"] = "Option_Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование</h2>

<h4>Опции</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Option_Edit" method="post" asp-controller="Option" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" value="@ViewBag.OptionId" name="OptionId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Название</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Опции", "Option_Index")
</div>

HotelProject/Views/Option/Option_Index.cshtml
@model IEnumerable<HotelProject.Models.Option>
@{
    ViewData["Title"] = "Option_Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Опции</h2>

@if (TempData["Option Add"] != null)
{
    <div class="alert alert-success">
        @TempData["Option Add"]
    </div>
}
@if (TempData["Option Edit"] != null)
{
    <div class="alert alert-success">
        @TempData["Option Edit"]
    </div>
}
@if (TempData["Option Delete"] != null)
{
    <div class="alert alert-success">
        @TempData["Option Delete"]
    </div>
}


<p>
    @Html.ActionLink("Добавить новую опцию", "Option_Add", "", htmlAttributes: new { @class = "btn btn-success" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-action="Option_Edit" asp-route-id="@item.Id">Редактировать</a> |
                    <a asp-action="Option_Details" asp-route-id="@item.Id">Детали</a> |
                    <a asp-action="Option_Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>